const phrases = [
  "One of these looks might  <br /> be your new look.",
  "Every shape in every color <br /> as glasses AND sunglasses.",
  "To see better. <br /> To see in the sun. <br /> To see better in the sun.",
  "Frame <br /> Correction lenses <br /> 150 Eur (most of the time)",
  "As easy as <br />  EINS, ZWEI, DREI.",
  "Ok, maybe as easy as <br /> EINS, ZWEI, DREI, <br /> VIER, FÜNF.",
  "Handcrafted from acetate.",
  "Keep scrolling. <br /> There's a lot to see.",
  "Fab photos <br /> by Kira & Jonas.",
  "2 new colors – <br /> Dolomite & Glacier.",
  "2 new models – <br /> VIER & FÜNF.",
  "You've scrolled one fourth  <br />  of the way. Nice.",
  "Hej, hej!",
  "Time for a chat? <br />  Call David <br /> +49 151 23041534.",
  "Handcrafted from acetate",
  "Finally, all over Europe.",
  "Fab photos <br /> by Kira & Jonas.",
  "Nice, simple, and simply <br /> nice.",
  "Questions? <br /> The FAQ will help.",
  "One of these looks might  <br /> be your new look.",
  "Every shape in every color <br /> as glasses AND sunglasses.",
  "To see better. <br /> To see in the sun. <br /> To see better in the sun.",
  "Frame <br /> Correction lenses <br /> 150 Eur (most of the time)",
  "As easy as <br />  EINS, ZWEI, DREI.",
  "Ok, maybe as easy as <br /> EINS, ZWEI, DREI, <br /> VIER, FÜNF.",
  "Handcrafted from acetate.",
  "Keep scrolling. <br /> There's a lot to see.",
  "Fab photos <br /> by Kira & Jonas.",
  "2 new colors – <br /> Dolomite & Glacier.",
  "2 new models – <br /> VIER & FÜNF.",
  "You've scrolled one fourth  <br />  of the way. Nice.",
  "Hej, hej!",
  "Time for a chat? <br />  Call David <br /> +49 151 23041534.",
  "Handcrafted from acetate",
  "Finally, all over Europe.",
  "Fab photos <br /> by Kira & Jonas.",
  "Nice, simple, and simply <br /> nice.",
  "Questions? <br /> The FAQ will help.",
];

export default phrases;